--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.1.24.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 12. 19. 14:49:06
-- Server version: 10.4.32
--

SET NAMES 'utf8';
