--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.1.24.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 2025. 01. 19. 10:25:17
-- Server version: 10.4.32
--

SET NAMES 'utf8';
